import React, { useState } from 'react';
import {
  HelpCircle,
  ShieldCheck,
  ShieldAlert,
  CheckCircle2,
  AlertTriangle,
  Award,
  RotateCcw,
  Sparkles,
  ArrowRight,
  FileCheck2,
  ChevronRight
} from 'lucide-react';
import { useApp } from '../../context/AppContext';

interface DiagnosticQuestion {
  id: number;
  scenario: string;
  question: string;
  options: {
    text: string;
    isSafe: boolean;
    explanation: string;
  }[];
}

export const FraudAssessmentQuiz: React.FC = () => {
  const { user, awardXp, setActiveTab, playSound, triggerConfetti } = useApp();

  const questions: DiagnosticQuestion[] = [
    {
      id: 1,
      scenario: 'You are selling an air conditioner on an online classifieds portal. The buyer sends a QR code on WhatsApp and tells you to scan it in PhonePe to receive their ₹12,000 deposit.',
      question: 'What is the correct protocol according to NPCI security standards?',
      options: [
        {
          text: 'Scan the QR code and enter your UPI PIN to approve the credit.',
          isSafe: false,
          explanation: 'Dangerous! Entering your UPI PIN debits money from your account. You NEVER enter a PIN to receive money.'
        },
        {
          text: 'Refuse to scan any QR code or enter PIN. Inform buyer that receiving funds only requires your UPI ID or phone number.',
          isSafe: true,
          explanation: 'Spot on! UPI PIN is solely for debiting funds. No QR scanning is ever required to receive payments.'
        },
        {
          text: 'Scan the QR on a friend\'s phone so your personal bank account is protected.',
          isSafe: false,
          explanation: 'This merely transfers the financial loss to your friend\'s bank account.'
        }
      ]
    },
    {
      id: 2,
      scenario: 'A caller claiming to be from your bank states your debit card has been used on an international shopping portal. They say they are reversing the charge right now and need you to read the 6-digit cancellation OTP sent to your phone.',
      question: 'What should you do?',
      options: [
        {
          text: 'Quickly read the code before the 60-second gateway countdown expires.',
          isSafe: false,
          explanation: 'Critical Error! The code is an authorization OTP generated by the scammer attempting to debit your card.'
        },
        {
          text: 'Disconnect the call immediately. Read the SMS text carefully and call the bank number on the back of your card.',
          isSafe: true,
          explanation: 'Flawless action! Banks never require customer OTPs to cancel unauthorized charges.'
        },
        {
          text: 'Give them the first 3 digits only as proof of identity.',
          isSafe: false,
          explanation: 'Never disclose partial OTPs or credentials to unverified callers.'
        }
      ]
    },
    {
      id: 3,
      scenario: 'You receive a video call on Skype or WhatsApp from a uniformed officer sitting in front of a police backdrop, claiming a courier with contraband was seized in your name and you are under "Digital Arrest".',
      question: 'What is the legal reality of "Digital Arrest"?',
      options: [
        {
          text: 'Digital Arrest is a recognized legal procedure introduced in cyber courts in 2024.',
          isSafe: false,
          explanation: 'False. Digital Arrest does not exist under Indian Penal Code, Bharatiya Nyaya Sanhita, or any global law.'
        },
        {
          text: 'There is no such legal concept. Police and CBI never conduct arrests or demand money transfers over video calls.',
          isSafe: true,
          explanation: 'Correct! Digital Arrest is 100% fraudulent extortion. Terminate the call and dial 1930.'
        },
        {
          text: 'You should negotiate to pay a 50% security deposit to an RBI verification account.',
          isSafe: false,
          explanation: 'The verification account is a fraudulent mule account operated by syndicates.'
        }
      ]
    },
    {
      id: 4,
      scenario: 'Your transaction on a food delivery app fails. You search Google for customer support and find a mobile number (+91 98210...). The person asks you to download "AnyDesk" to fix the refund cache.',
      question: 'What does installing AnyDesk permit the caller to do?',
      options: [
        {
          text: 'It safely syncs your app cache with the company\'s cloud server.',
          isSafe: false,
          explanation: 'AnyDesk is remote screen-sharing software, not an app cache cleaner.'
        },
        {
          text: 'It gives the caller full visibility and remote control over your phone screen, allowing them to read incoming bank OTPs.',
          isSafe: true,
          explanation: 'Precise! Screen-sharing software allows fraudsters to harvest passwords and OTPs in real-time.'
        },
        {
          text: 'It is harmless as long as you keep your phone on silent mode.',
          isSafe: false,
          explanation: 'Silent mode has no bearing on screen mirror surveillance.'
        }
      ]
    },
    {
      id: 5,
      scenario: 'An SMS arrives: "Dear SBI customer, your YONO NetBanking will be blocked tonight due to pending KYC docs. Update now at http://sbi-verification-portal.xyz/login".',
      question: 'How can you identify that this website is fraudulent?',
      options: [
        {
          text: 'The domain ends in `.xyz` rather than official banking domains `.sbi` or `.bank.sbi`.',
          isSafe: true,
          explanation: 'Spot on! SBI owns the dedicated `.sbi` domain. Any third-party TLD (.xyz, .top, .site) is phishing.'
        },
        {
          text: 'Because it was sent during evening hours.',
          isSafe: false,
          explanation: 'While timing is suspicious, domain address verification is the definitive technical proof.'
        },
        {
          text: 'Banks only update KYC by sending physical registered postal letters.',
          isSafe: false,
          explanation: 'Banks do conduct digital KYC, but strictly inside verified mobile apps or branches.'
        }
      ]
    }
  ];

  const [currentIdx, setCurrentIdx] = useState(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});
  const [isCompleted, setIsCompleted] = useState(false);

  const currentQ = questions[currentIdx];
  const userAns = selectedAnswers[currentIdx];

  const handleSelectAnswer = (optionIdx: number) => {
    playSound('click');
    setSelectedAnswers((prev) => ({ ...prev, [currentIdx]: optionIdx }));
  };

  const handleNext = () => {
    playSound('click');
    if (currentIdx < questions.length - 1) {
      setCurrentIdx((prev) => prev + 1);
    } else {
      // Complete quiz
      setIsCompleted(true);
      playSound('success');
      triggerConfetti();
      awardXp(150);
    }
  };

  const calculateScore = () => {
    let correct = 0;
    questions.forEach((q, idx) => {
      const selected = selectedAnswers[idx];
      if (selected !== undefined && q.options[selected].isSafe) {
        correct += 1;
      }
    });
    return Math.round((correct / questions.length) * 100);
  };

  const finalScore = calculateScore();
  const isEligibleForCert = finalScore >= 80;

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="p-6 sm:p-8 rounded-3xl bg-white border border-slate-200/80 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-semibold mb-2">
            <HelpCircle className="w-3.5 h-3.5 text-blue-600" />
            <span>Standardized Diagnostic Examination</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
            Financial Fraud Awareness Assessment
          </h1>
          <p className="text-slate-500 text-xs sm:text-sm max-w-xl">
            Evaluate your defense readiness across 5 high-risk dilemmas. Score 80% or above to unlock the official Cyber Guardian Certificate.
          </p>
        </div>

        <div className="p-4 rounded-2xl bg-slate-50 border border-slate-100 self-start md:self-auto">
          <div className="text-xs font-bold text-slate-900">Passing Threshold</div>
          <div className="text-xs text-emerald-600 font-extrabold mt-0.5">80% Required for Certificate</div>
        </div>
      </div>

      {!isCompleted ? (
        /* Active Quiz Question Card */
        <div className="p-6 sm:p-8 rounded-3xl bg-white border border-slate-200/80 shadow-xs space-y-6 max-w-3xl mx-auto">
          {/* Progress Header */}
          <div className="flex items-center justify-between text-xs font-bold text-slate-400 border-b border-slate-100 pb-3">
            <span>Question {currentIdx + 1} of {questions.length}</span>
            <div className="flex gap-1.5">
              {questions.map((_, i) => (
                <div
                  key={i}
                  className={`w-6 h-1.5 rounded-full ${
                    i === currentIdx
                      ? 'bg-blue-600'
                      : selectedAnswers[i] !== undefined
                      ? 'bg-emerald-500'
                      : 'bg-slate-200'
                  }`}
                />
              ))}
            </div>
          </div>

          {/* Scenario Context */}
          <div className="p-4 rounded-2xl bg-blue-50/70 border border-blue-100 text-xs sm:text-sm text-blue-950 leading-relaxed font-medium">
            <strong>Scenario:</strong> {currentQ.scenario}
          </div>

          <h3 className="font-extrabold text-slate-900 text-sm sm:text-base leading-snug">
            {currentQ.question}
          </h3>

          {/* Options */}
          <div className="space-y-3">
            {currentQ.options.map((opt, oIdx) => {
              const isSelected = userAns === oIdx;
              return (
                <button
                  key={oIdx}
                  onClick={() => handleSelectAnswer(oIdx)}
                  className={`w-full p-4 rounded-2xl text-left text-xs sm:text-sm font-medium transition-all border flex items-start gap-3 ${
                    isSelected
                      ? 'bg-blue-50/80 border-blue-500 ring-2 ring-blue-500/20 text-blue-950 font-bold'
                      : 'bg-white border-slate-200 hover:border-slate-300 text-slate-800'
                  }`}
                >
                  <div
                    className={`w-4 h-4 rounded-full mt-0.5 border flex items-center justify-center shrink-0 ${
                      isSelected
                        ? 'border-blue-600 bg-blue-600 text-white'
                        : 'border-slate-300 bg-white'
                    }`}
                  >
                    {isSelected && <div className="w-1.5 h-1.5 rounded-full bg-white" />}
                  </div>
                  <span className="leading-snug">{opt.text}</span>
                </button>
              );
            })}
          </div>

          <button
            disabled={userAns === undefined}
            onClick={handleNext}
            className="w-full py-3 rounded-xl bg-blue-600 hover:bg-blue-700 disabled:bg-slate-200 disabled:text-slate-400 text-white font-bold text-xs sm:text-sm shadow-xs transition-colors flex items-center justify-center gap-2"
          >
            <span>{currentIdx < questions.length - 1 ? 'Next Question' : 'Submit Assessment'}</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      ) : (
        /* Results Card */
        <div className="p-8 rounded-3xl bg-white border border-slate-200/80 shadow-xs text-center space-y-6 max-w-xl mx-auto">
          <div
            className={`w-20 h-20 mx-auto rounded-3xl flex items-center justify-center shadow-lg ${
              isEligibleForCert
                ? 'bg-emerald-600 text-white shadow-emerald-600/30'
                : 'bg-amber-500 text-white shadow-amber-500/30'
            }`}
          >
            {isEligibleForCert ? <Award className="w-10 h-10" /> : <AlertTriangle className="w-10 h-10" />}
          </div>

          <div>
            <div className="text-xs font-bold uppercase tracking-wider text-slate-400">
              Assessment Results
            </div>
            <div className="text-4xl font-black text-slate-900 mt-1">{finalScore}%</div>
            <p className="text-xs text-slate-500 mt-2">
              {isEligibleForCert
                ? 'Outstanding performance! You displayed exceptional fraud defense instincts.'
                : 'Good attempt! Review missed scenarios and retake the test to qualify for certification.'}
            </p>
          </div>

          {/* Certificate unlock card */}
          {isEligibleForCert && (
            <div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-left flex items-center justify-between">
              <div>
                <div className="text-xs font-bold text-emerald-950">
                  Certified Cyber Guardian Credential Unlocked!
                </div>
                <div className="text-[11px] text-emerald-800">
                  Grade A+ Distinction · Verifiable Credential
                </div>
              </div>
              <button
                onClick={() => setActiveTab('certificates')}
                className="px-3 py-1.5 rounded-xl bg-emerald-600 text-white font-bold text-xs"
              >
                View Certificate
              </button>
            </div>
          )}

          <div className="flex items-center justify-center gap-3 pt-2">
            <button
              onClick={() => {
                setCurrentIdx(0);
                setSelectedAnswers({});
                setIsCompleted(false);
              }}
              className="px-4 py-2.5 rounded-xl border border-slate-200 text-slate-700 hover:bg-slate-100 font-semibold text-xs flex items-center gap-1.5"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Retake Quiz</span>
            </button>

            <button
              onClick={() => setActiveTab('dashboard')}
              className="px-6 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-xs"
            >
              Dashboard
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
