import {
  SimulationScenario,
  NewsArticle,
  CourseModule,
  LearningPathNode,
  AchievementItem,
  LeaderboardUser,
  VoiceScenario,
  SMSItem,
  HeatmapStateData,
  UserProfile
} from '../types';

export const INITIAL_USER: UserProfile = {
  name: 'Harshal Mahajan',
  email: 'harshalmahajan7350@gmail.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  level: 4,
  xp: 1450,
  nextLevelXp: 2000,
  streakDays: 7,
  overallScore: 84,
  riskRating: 'Very Low Risk',
  title: 'Senior Cyber Defender',
  collegeOrOrg: 'National Institute of Technology',
  city: 'Pune, India',
  completedSimulationIds: ['sim_otp_01', 'sim_qr_01', 'sim_upi_collect_01', 'sim_kyc_01'],
  earnedCertificateIds: ['cert_guardian_01', 'cert_upi_01'],
  unlockedAchievementIds: ['ach_otp_master', 'ach_qr_hunter', 'ach_first_blood', 'ach_streak_7'],
  categoryScores: {
    otp: 92,
    qr: 88,
    upi: 85,
    phishing: 80,
    kyc: 82,
    voice: 78,
    investment: 75,
    socialEngineering: 86
  }
};

export const GLOBAL_FRAUD_STATS = {
  totalLossPreventedUSD: '$4.2B',
  totalLossPreventedINR: '₹34,800 Cr',
  peopleTrainedCount: '2,480,120+',
  mostCommonScam: 'UPI Collect Request & QR Scam',
  trendingScam: 'Digital Arrest / Fake Police Video Call',
  scamSuccessRateDrop: '-64% after 3 simulations',
  reportedIncidents2026: '1.42M',
  avgReportedLossINR: '₹68,400'
};

export const SIMULATION_SCENARIOS: SimulationScenario[] = [
  {
    id: 'sim_otp_01',
    title: 'OTP Scam: The Bank Server Sync Trap',
    category: 'OTP Fraud',
    difficulty: 'Beginner',
    estimatedMinutes: 3,
    tagline: 'A polite caller claims an unauthorized transaction of ₹14,500 is pending.',
    realWorldContext: 'Victims often panic when told money has already left their account, making them eager to read back the cancellation OTP.',
    iconName: 'KeyRound',
    victimLossStat: '₹1,200 Cr lost in 2025 across India to OTP sharing frauds',
    learningTakeaways: [
      'Banks never ask for OTP under any circumstance.',
      'There is no such thing as a "cancellation OTP" or "refund authorization code".',
      'The text inside the SMS says "NEVER SHARE WITH ANYONE FOR ANY REASON".'
    ],
    steps: [
      {
        id: 'otp_step_1',
        prompt: 'You receive an urgent phone call from someone claiming to be HDFC Bank Fraud Prevention Unit.',
        contextNarrative: '"Sir, we noticed an international transaction attempt of ₹14,500 on your debit card from Lagos. Did you authorize this?" You reply: "No, absolutely not!"',
        screenType: 'phone_call',
        screenMockupData: {
          sender: '+91 98201 XXXXX (Spoofed: HDFC Fraud Desk)',
          messageText: 'Caller: "Do not worry sir, I am immediately reversing the payment. I sent a 6-digit cancellation token to your SMS. Read it out quickly before the 60-second gateway locks!"'
        },
        options: [
          {
            id: 'opt_otp_share',
            text: 'Quickly open SMS and read the 6-digit code to stop the fraudulent charge.',
            isSafe: false,
            explanation: 'Critical Error! The code was not a cancellation token—it was an authorization OTP generated by the scammer attempting to debit your card.',
            redFlagsDiscovered: ['Urgency clock pressure (60-second gateway)', 'Requesting confidential OTP', 'Caller initiated contact claiming urgent debit'],
            xpEarned: 0
          },
          {
            id: 'opt_otp_read_text',
            text: 'Check the SMS carefully, read the wording, and refuse to disclose the code.',
            isSafe: true,
            explanation: 'Excellent move! The SMS explicitly states: "OTP to DEBIT ₹14,500 to Merchant XYZ. Do not share with bank officials."',
            redFlagsDiscovered: ['SMS text contradicts caller claim', 'Legitimate banks never reverse payments using customer OTPs'],
            xpEarned: 50
          },
          {
            id: 'opt_otp_hangup',
            text: 'Hang up immediately and call the official bank number on the back of your debit card.',
            isSafe: true,
            explanation: 'Perfect Golden Rule! Always verify independently using official channels printed on your physical card.',
            redFlagsDiscovered: ['Unverified caller', 'Spoofed caller ID'],
            xpEarned: 75
          }
        ]
      },
      {
        id: 'otp_step_2',
        prompt: 'The scammer calls back angrily from another number: "Sir, your account will be frozen by RBI if you don\'t cooperate!"',
        contextNarrative: 'They are using fear and authority intimidation to break your skepticism.',
        screenType: 'phone_call',
        options: [
          {
            id: 'opt_otp_yield',
            text: 'Apologize and give the last 3 digits of the OTP to show goodwill.',
            isSafe: false,
            explanation: 'Never negotiate with scammers. Any partial credential helps brute force verification.',
            redFlagsDiscovered: ['Fear manipulation', 'Threat of government/RBI freezing'],
            xpEarned: 0
          },
          {
            id: 'opt_otp_report',
            text: 'Block the number and dial 1930 (National Cyber Crime Helpline) or report in bank app.',
            isSafe: true,
            explanation: 'Outstanding response. Dialing 1930 logs the suspect number across the national financial cyber fraud reporting portal.',
            redFlagsDiscovered: ['Intimidation tactics', 'Bogus regulatory threats'],
            xpEarned: 100
          }
        ]
      }
    ]
  },
  {
    id: 'sim_support_01',
    title: 'Fake Customer Support: The Search Engine Trap',
    category: 'Customer Support',
    difficulty: 'Intermediate',
    estimatedMinutes: 4,
    tagline: 'Your ₹500 grocery transaction failed. You searched Google for PhonePe toll-free number.',
    realWorldContext: 'Scammers buy Google Ads and edit Google Maps listings to display their personal mobile numbers as official customer support.',
    iconName: 'Headphones',
    victimLossStat: 'Over 40% of first-time UPI victims found the fraudster\'s contact via Google Search',
    learningTakeaways: [
      'Never search Google for customer support phone numbers of UPI or payment apps.',
      'Always use in-app Help & Support tickets inside PhonePe, GPay, or Paytm.',
      'Toll-free numbers never begin with standard personal 10-digit mobile numbers.'
    ],
    steps: [
      {
        id: 'supp_step_1',
        prompt: 'You call the number listed on a top Google search result: "PhonePe 24x7 Helpline +91 82910 44921".',
        contextNarrative: 'A polite person answers: "Thank you for calling PhonePe Support. My name is Vikram. How may I assist your refund today?"',
        screenType: 'phone_call',
        screenMockupData: {
          sender: '+91 82910 44921 (Google Result: PhonePe Helpdesk)',
          messageText: '"Yes sir, I see the pending ₹500 transaction. To process direct wallet refund to your bank, please open your PhonePe app and go to Notifications."'
        },
        options: [
          {
            id: 'opt_supp_follow',
            text: 'Follow his instructions inside the app while keeping him on the call.',
            isSafe: false,
            explanation: 'Dangerous! Real customer care does not walk you through real-time app approvals over a random 10-digit phone call.',
            redFlagsDiscovered: ['Personal 10-digit mobile number for support', 'Live instruction to click app notifications'],
            xpEarned: 10
          },
          {
            id: 'opt_supp_check_official',
            text: 'Hang up and open the PhonePe app directly to check official support channels.',
            isSafe: true,
            explanation: 'Spot on! PhonePe customer care operates strictly via in-app tickets or verified IVR 080-68727374.',
            redFlagsDiscovered: ['Unverified Google search snippet', 'Third-party ad disguised as helpline'],
            xpEarned: 70
          }
        ]
      }
    ]
  },
  {
    id: 'sim_kyc_01',
    title: 'KYC Update Scam: Account Suspension Threat',
    category: 'KYC Scam',
    difficulty: 'Beginner',
    estimatedMinutes: 3,
    tagline: '"Dear customer, your SBI YONO account will be blocked today due to pending KYC."',
    realWorldContext: 'Mass SMS campaigns spoof bank names and create panic about frozen salaries or pension accounts.',
    iconName: 'ShieldAlert',
    victimLossStat: '₹890 Cr lost to spoofed KYC links in India in the past 12 months',
    learningTakeaways: [
      'Banks do not update KYC via random SMS web links.',
      'Official KYC is done via branch visit or secured in-app Video KYC.',
      'Look at domain names: `sbi-kyc-verify.vip` is completely fake.'
    ],
    steps: [
      {
        id: 'kyc_step_1',
        prompt: 'You receive an SMS from sender ID "VM-SBIN-KYC".',
        contextNarrative: 'The message states: "Dear SBI user, your NetBanking access is restricted due to pending KYC docs. Click http://sbi-verification-secure.in/update to update PAN & Aadhaar within 12 hours."',
        screenType: 'sms',
        screenMockupData: {
          sender: 'VM-SBIN-KYC',
          messageText: 'URGENT: SBI Account will be deactivated. Update KYC now at http://sbi-verification-secure.in/update'
        },
        options: [
          {
            id: 'opt_kyc_click',
            text: 'Click the link to check what documents are missing before your account gets blocked.',
            isSafe: false,
            explanation: 'High risk! Clicking suspicious phishing links can download spyware APKs or take you to cloned credential harvesters.',
            redFlagsDiscovered: ['Unsecured HTTP / non-official domain', 'Threat of account deactivation in 12 hours', 'Third-party domain .in instead of official onlinesbi.sbi'],
            xpEarned: 0
          },
          {
            id: 'opt_kyc_examine_domain',
            text: 'Examine the URL domain and compare it with the official bank domain (onlinesbi.sbi).',
            isSafe: true,
            explanation: 'Brilliant catch. SBI strictly uses domains ending in `.sbi` or `.bank.sbi`. Any `-verification-secure` is a phishing domain.',
            redFlagsDiscovered: ['Phishing domain variation', 'Artificial urgency'],
            xpEarned: 60
          },
          {
            id: 'opt_kyc_forward_spam',
            text: 'Forward the message to 1909 (Do Not Disturb spam registry) and report in Chakshu portal.',
            isSafe: true,
            explanation: 'Government and telecom operators use the Sanchar Saathi / Chakshu portal to deactivate malicious SMS sender IDs.',
            redFlagsDiscovered: ['Unsolicited SMS phishing', 'Spoofed alpha header'],
            xpEarned: 90
          }
        ]
      }
    ]
  },
  {
    id: 'sim_qr_01',
    title: 'QR Code Scam: The "Scan to Receive Money" Myth',
    category: 'QR Code Scam',
    difficulty: 'Beginner',
    estimatedMinutes: 3,
    tagline: 'You listed an old sofa on OLX. A buyer offers to pay immediately via QR code.',
    realWorldContext: 'One of the most widespread UPI tricks: Scammers convince sellers that scanning a QR code is required to credit money into their account.',
    iconName: 'QrCode',
    victimLossStat: 'Most common OLX / marketplace scam targeting innocent individual sellers',
    learningTakeaways: [
      'YOU NEVER SCAN A QR CODE TO RECEIVE MONEY.',
      'YOU NEVER ENTER YOUR UPI PIN TO RECEIVE MONEY.',
      'Scanning a QR code and entering PIN ALWAYS debits money from your account.'
    ],
    steps: [
      {
        id: 'qr_step_1',
        prompt: 'The buyer messages you on WhatsApp with an image of a QR code.',
        contextNarrative: '"Sir, I am an army officer posted in cantonment. My company account only sends payments through Merchant Barcode. Scan this QR in your Google Pay, and ₹8,000 will be credited directly."',
        screenType: 'whatsapp',
        screenMockupData: {
          sender: 'Capt. R. Sharma (Indian Army DP)',
          messageText: 'Payment receipt QR code attached. Open GPay -> Scan -> Enter PIN -> ₹8,000 credit success.',
          attachmentName: 'Army_Canteen_Refund_QR_8000.png'
        },
        options: [
          {
            id: 'opt_qr_scan_pin',
            text: 'Scan the QR code and enter your 6-digit UPI PIN when prompted.',
            isSafe: false,
            explanation: 'Catastrophic Error! Entering your UPI PIN debited ₹8,000 from your account! You NEVER enter a PIN to receive money.',
            redFlagsDiscovered: ['Entering PIN to receive funds', 'Army officer / CSD impersonation to build trust', 'Fake merchant QR logic'],
            xpEarned: 0
          },
          {
            id: 'opt_qr_refuse_pin',
            text: 'Refuse firmly: "Receiving UPI money does not require scanning QR or entering PIN. Just transfer to my UPI ID or mobile number."',
            isSafe: true,
            explanation: 'Masterclass response! To receive money, a sender only needs your UPI ID (VPA) or phone number. No PIN or QR scanning is ever required.',
            redFlagsDiscovered: ['Fundamental UPI rule violation: PIN is strictly for debiting', 'Fake buyer urgency'],
            xpEarned: 85
          }
        ]
      }
    ]
  },
  {
    id: 'sim_phish_01',
    title: 'Phishing Link Scam: Fake NetBanking Portal',
    category: 'Phishing Link',
    difficulty: 'Intermediate',
    estimatedMinutes: 4,
    tagline: 'An email claims your credit card reward points worth ₹9,450 are expiring tonight.',
    realWorldContext: 'Cloned banking portals look 99% identical to the real bank, down to the copyright notice and logos.',
    iconName: 'ExternalLink',
    victimLossStat: 'Fake reward point links steal customer credentials and immediately trigger international card debits',
    learningTakeaways: [
      'Check the browser address bar for official HTTPS certificate and exact domain spelling.',
      'Banks never ask for Debit Card CVV and ATM PIN together on a website form.',
      'Reward points can always be redeemed safely inside your bank\'s genuine mobile app.'
    ],
    steps: [
      {
        id: 'phish_step_1',
        prompt: 'You open a link in an email: `http://hdfc-rewardpoints-claim.site/login`',
        contextNarrative: 'The page has the exact HDFC blue logo, a banner saying "Redeem 9,450 points for cash voucher", and a form asking for: Customer ID, Password, Card Number, Expiry, CVV, and ATM PIN.',
        screenType: 'bank_portal',
        screenMockupData: {
          url: 'http://hdfc-rewardpoints-claim.site/login',
          sender: 'rewards@hdfc-notification-desk.com',
          messageText: 'Claim Your ₹9,450 Unclaimed Rewards Now! Expires 11:59 PM.'
        },
        options: [
          {
            id: 'opt_phish_fill',
            text: 'Fill the form with your card details to cash in the reward points.',
            isSafe: false,
            explanation: 'Severe credential loss! Legitimate banks NEVER ask for your ATM PIN on a web portal.',
            redFlagsDiscovered: ['Insecure HTTP domain (.site TLD)', 'Asking for ATM PIN and CVV on same page', 'Unrealistic cash voucher offer'],
            xpEarned: 0
          },
          {
            id: 'opt_phish_close_app',
            text: 'Close the tab. Open the official HDFC Mobile App to check genuine reward points.',
            isSafe: true,
            explanation: 'Perfect discipline. Genuine reward points are viewable under "Cards > Rewards" in the authentic app.',
            redFlagsDiscovered: ['Suspicious domain extension', 'Redundant credential harvesting'],
            xpEarned: 75
          }
        ]
      }
    ]
  },
  {
    id: 'sim_upi_collect_01',
    title: 'UPI Collect Request Scam: The ₹1 Verification Trick',
    category: 'UPI Collect',
    difficulty: 'Beginner',
    estimatedMinutes: 3,
    tagline: 'A buyer sends a notification: "Payment Request from Merchant. Pay ₹4,999 to receive ₹5,000 refund."',
    realWorldContext: 'Scammers exploit the word "Pay" vs "Request" in payment apps, confusing users into approving collect requests.',
    iconName: 'IndianRupee',
    victimLossStat: 'Over ₹600 Cr lost annually to deceptive UPI Collect requests',
    learningTakeaways: [
      'A Collect Request takes money FROM you. It never sends money TO you.',
      'Reject and report any unfamiliar payment request in your UPI notifications.',
      'No merchant needs you to "pay a fee first" to receive a refund.'
    ],
    steps: [
      {
        id: 'collect_step_1',
        prompt: 'A popup appears on your Google Pay screen: "Radhey Trading has requested ₹4,999 from you. Note: Refund Token #9281".',
        contextNarrative: 'The caller on phone says: "Sir click Accept and enter PIN. The system will reverse it and add ₹5,000 to your balance immediately."',
        screenType: 'upi_app',
        screenMockupData: {
          appBrand: 'Google Pay',
          sender: 'Radhey Trading (Collect Request)',
          amount: '₹4,999.00',
          messageText: 'Tap Pay to approve payment to Radhey Trading'
        },
        options: [
          {
            id: 'opt_collect_pay',
            text: 'Click "Pay" and enter your UPI PIN as directed by the caller.',
            isSafe: false,
            explanation: 'Money Lost! You authorized a collect request. ₹4,999 was instantly deducted from your bank balance.',
            redFlagsDiscovered: ['The button says "Pay" not "Receive"', 'Entering PIN to receive funds', 'Misleading note in transaction remark'],
            xpEarned: 0
          },
          {
            id: 'opt_collect_decline_block',
            text: 'Click "Decline", check "Report Spam", and block the VPA.',
            isSafe: true,
            explanation: 'Ideal defense. Reporting the VPA flags the merchant ID across NPCI network, protecting other users.',
            redFlagsDiscovered: ['Collect request inverted into fake refund', 'Spam UPI handle abuse'],
            xpEarned: 80
          }
        ]
      }
    ]
  },
  {
    id: 'sim_invest_01',
    title: 'Investment Scam: "Guaranteed 300% Returns" Group',
    category: 'Investment Fraud',
    difficulty: 'Intermediate',
    estimatedMinutes: 4,
    tagline: 'You are added to a Telegram group with 50,000 members sharing screenshots of massive daily profits.',
    realWorldContext: 'Organized syndicates run fake crypto exchanges and staged trading groups where group members are paid actors or bots.',
    iconName: 'TrendingUp',
    victimLossStat: '₹14,000 Cr lost in 2024-2025 in fake stock market and crypto group frauds',
    learningTakeaways: [
      'Guaranteed high returns do not exist. Any promise above 12-15% guaranteed is guaranteed fraud.',
      'Unregulated trading apps and APKs display fake profit balances to extract larger deposits.',
      'When you try to withdraw, they demand a 20% "tax" or "handling fee".'
    ],
    steps: [
      {
        id: 'invest_step_1',
        prompt: 'You deposit ₹2,000 to test the app. In 2 hours, the screen shows your balance grew to ₹7,800!',
        contextNarrative: 'The group "mentor" messages you privately: "Congratulations! You qualified for the VIP Institutional Pool. Deposit ₹50,000 now to unlock a guaranteed ₹2,50,000 return by tomorrow morning."',
        screenType: 'generic',
        screenMockupData: {
          appBrand: 'ApexGlobalTrader.apk (Unofficial)',
          amount: '₹7,800.00 (Fake Profit)',
          messageText: 'VIP Trade Tier Unlocked: Deposit ₹50,000 to withdraw total ₹2,57,800'
        },
        options: [
          {
            id: 'opt_invest_deposit_more',
            text: 'Transfer ₹50,000 via IMPS to the personal saving account provided by the mentor.',
            isSafe: false,
            explanation: 'Major Loss! The initial small profit was a deliberate lure (pig butchering scam). Once you send large sums, they block your account.',
            redFlagsDiscovered: ['Unrealistic guaranteed returns', 'Money sent to personal accounts rather than SEBI-registered brokers', 'Side-loaded APK not on Google Play'],
            xpEarned: 0
          },
          {
            id: 'opt_invest_exit_report',
            text: 'Recognize the Pig Butchering scheme. Refuse to send any money and report the group to Cyber Cell.',
            isSafe: true,
            explanation: 'Spot on! Real financial advisors are SEBI-registered and never guarantee risk-free multiplier returns on Telegram.',
            redFlagsDiscovered: ['Unrealistic profit illusion', 'Social proof manipulation with bot screenshots'],
            xpEarned: 90
          }
        ]
      }
    ]
  },
  {
    id: 'sim_deepfake_01',
    title: 'Deepfake & Voice Fraud: The Distressed Son',
    category: 'Deepfake & Voice',
    difficulty: 'Advanced',
    estimatedMinutes: 4,
    tagline: 'An elderly parent receives an urgent call sounding exactly like their child crying from police station.',
    realWorldContext: 'AI voice cloners need only 3 seconds of audio from Instagram reels or YouTube to replicate family members\' voices.',
    iconName: 'Mic',
    victimLossStat: 'Surging across metros, targeting parents and senior citizens with urgent bail extortion',
    learningTakeaways: [
      'Establish a secret family emergency safe-word in advance.',
      'Always hang up and call the family member back on their known regular phone number.',
      'Never send immediate bail money via UPI or cash pickup without independent visual confirmation.'
    ],
    steps: [
      {
        id: 'deepfake_step_1',
        prompt: 'A tearful voice that sounds 100% identical to your brother calls from an unknown number.',
        contextNarrative: '"Bhaiya! Please help me! I was in a friend\'s car and police found contraband. They are going to remand me unless you pay ₹40,000 fine to the inspector right now!"',
        screenType: 'phone_call',
        screenMockupData: {
          sender: '+91 91024 XXXXX',
          messageText: 'Deepfake Voice: "Speak to Inspector Rathore quickly, they are taking my phone away!"'
        },
        options: [
          {
            id: 'opt_deepfake_panic_pay',
            text: 'Panic, ask for the inspector\'s UPI ID, and transfer ₹40,000 immediately.',
            isSafe: false,
            explanation: 'Critical Trap! The voice was an AI clone created from social media audio clips. Your brother was safe at work.',
            redFlagsDiscovered: ['Emotional blackmail and intense panic', 'Calling from unknown number', 'Demand for immediate instant settlement'],
            xpEarned: 0
          },
          {
            id: 'opt_deepfake_verify_direct',
            text: 'Stay calm. Ask a personal secret question or call your brother directly on his normal phone.',
            isSafe: true,
            explanation: 'Flawless verification. You dialed his regular number; he answered normally from his office, completely unaware of the fake call.',
            redFlagsDiscovered: ['Voice cloning artifact', 'Failure to answer personal verification question'],
            xpEarned: 95
          }
        ]
      }
    ]
  },
  {
    id: 'sim_wa_01',
    title: 'WhatsApp Scam: The "Part-Time Review Job" Lure',
    category: 'WhatsApp Scam',
    difficulty: 'Beginner',
    estimatedMinutes: 3,
    tagline: '"Earn ₹3,000 to ₹8,000 daily by simply rating hotels on Google Maps from home."',
    realWorldContext: 'Automated WhatsApp bots target millions of job seekers with easy online tasks that escalate into prepaid crypto deposit traps.',
    iconName: 'MessageSquare',
    victimLossStat: 'Top gateway scam recruiting young college students and job seekers into financial traps',
    learningTakeaways: [
      'Legitimate companies never hire or pay freelancers via anonymous WhatsApp business numbers.',
      'Task scams always pay small ₹150 amounts initially to gain trust before demanding "prepaid deposits".',
      'Never join private Telegram task groups for reviewing products.'
    ],
    steps: [
      {
        id: 'wa_step_1',
        prompt: 'You receive an unsolicited WhatsApp message from an international business account (+62 881...).',
        contextNarrative: '"Hello! I am HR Manager from Global Media. We found your resume on LinkedIn. Work 30 mins a day rating restaurants on Google. We pay ₹150 per review directly to your UPI. Reply YES to start."',
        screenType: 'whatsapp',
        screenMockupData: {
          sender: '+62 881 9283 192 (HR Recruiter)',
          messageText: 'Earn ₹3,500/day. No qualification needed. Just 5 star review links.'
        },
        options: [
          {
            id: 'opt_wa_reply_yes',
            text: 'Reply "YES" and share your UPI ID to earn some quick pocket money.',
            isSafe: false,
            explanation: 'You entered the Task Scam funnel. After paying you ₹300, they will demand you invest ₹5,000 for "Prepaid Level 2" which you will never recover.',
            redFlagsDiscovered: ['Foreign country code (+62)', 'Unsolicited job offer without interview', 'Unrealistic pay for trivial review tasks'],
            xpEarned: 10
          },
          {
            id: 'opt_wa_block_report',
            text: 'Block the number immediately and report as spam to WhatsApp.',
            isSafe: true,
            explanation: 'Smart proactive defense. WhatsApp uses aggregated spam reports to ban entire bot farm clusters.',
            redFlagsDiscovered: ['Classic Part-time task scam pattern', 'Anonymous international sender'],
            xpEarned: 70
          }
        ]
      }
    ]
  },
  {
    id: 'sim_loan_01',
    title: 'Loan Approval Scam: Instant Loan App Trap',
    category: 'Instant Loan',
    difficulty: 'Intermediate',
    estimatedMinutes: 4,
    tagline: '"Instant ₹2,00,000 loan approved in 2 minutes without CIBIL score or documents."',
    realWorldContext: 'Predatory lending apps require users to grant full access to Contacts and Photo gallery, followed by extortion.',
    iconName: 'FileText',
    victimLossStat: 'Extortion and harassment through blackmailed contact lists has affected hundreds of thousands',
    learningTakeaways: [
      'Only borrow from RBI-regulated NBFCs or scheduled commercial banks.',
      'Never grant "Contacts" and "Photos" permission to loan utility apps.',
      'Legitimate lenders deduct processing fees from loan disbursement, never upfront.'
    ],
    steps: [
      {
        id: 'loan_step_1',
        prompt: 'You install a loan app from an APK link sent via SMS: "QuickCash-Instant.apk".',
        contextNarrative: 'Upon opening, the app demands: "Allow access to Contacts, Gallery, SMS, and Location to verify credit score."',
        screenType: 'generic',
        screenMockupData: {
          appBrand: 'QuickCash Instant',
          messageText: 'Grant permissions to proceed with ₹2,00,000 instant sanction.'
        },
        options: [
          {
            id: 'opt_loan_allow_perms',
            text: 'Grant all permissions so the automated algorithm can verify your profile.',
            isSafe: false,
            explanation: 'Dangerous privacy breach! The app clones your entire contact book and photo gallery to blackmail you for exorbitant interest.',
            redFlagsDiscovered: ['Excessive permissions (Contacts & Photos)', 'Sideloaded APK not approved on app stores', 'No RBI NBFC registration disclosed'],
            xpEarned: 0
          },
          {
            id: 'opt_loan_uninstall_check_rbi',
            text: 'Deny permissions and immediately uninstall. Verify loan providers on RBI\'s registered NBFC portal.',
            isSafe: true,
            explanation: 'Lifesaving action. RBI strictly prohibits digital lenders from accessing borrower mobile contacts and media galleries.',
            redFlagsDiscovered: ['Predatory permission harvesting', 'Illegal lending syndicate signature'],
            xpEarned: 85
          }
        ]
      }
    ]
  },
  {
    id: 'sim_refund_01',
    title: 'Refund Scam: The Electricity Bill Disconnection Hoax',
    category: 'Refund Scam',
    difficulty: 'Beginner',
    estimatedMinutes: 3,
    tagline: '"Dear Consumer, your electricity power will be disconnected at 9:30 PM due to unpaid bill."',
    realWorldContext: 'Scammers send panicky SMS alerts in late evenings when offices are closed, urging victims to call an "officer" to stop blackout.',
    iconName: 'Zap',
    victimLossStat: 'Frequent scam reported across Maharashtra, Gujarat, Delhi, and UP power consumers',
    learningTakeaways: [
      'Power utilities (MSEDCL, BSES, TNEB, etc.) send SMS from verified government headers (e.g., VM-MSPDCL), never personal mobile numbers.',
      'Official disconnections follow legal formal paper notices, not same-night SMS warnings.',
      'Bills can always be verified on the official discom website or municipal electricity counter.'
    ],
    steps: [
      {
        id: 'refund_step_1',
        prompt: 'At 8:15 PM, you get an SMS: "Dear Customer, your electricity will be disconnected tonight at 9:30 PM. Call Electricity Officer Verma at 98721 XXXXX immediately to clear pending bill."',
        contextNarrative: 'Your family is worried about sudden power cut during dinner.',
        screenType: 'sms',
        screenMockupData: {
          sender: '+91 98721 39182',
          messageText: 'Electricity power will be cut off tonight at 9:30 PM. Update your last month paid bill immediately.'
        },
        options: [
          {
            id: 'opt_refund_call_officer',
            text: 'Call Officer Verma right away and follow his instructions to make a quick ₹10 bill update payment.',
            isSafe: false,
            explanation: 'Trap sprung! The ₹10 link is a malicious screen-sharing link or phishing form that captures your card and PIN.',
            redFlagsDiscovered: ['Sent from personal 10-digit number instead of official Discom SMS header', 'Late night urgency threat', 'Personal phone number of "officer" in SMS'],
            xpEarned: 0
          },
          {
            id: 'opt_refund_check_app',
            text: 'Ignore the phone number. Open your electricity board\'s official portal or check your latest bill receipt.',
            isSafe: true,
            explanation: 'Smart thinking! Your official portal shows zero pending balance. Power utilities never assign individual mobile numbers for bill settlement.',
            redFlagsDiscovered: ['Manufactured blackout panic', 'Unverified sender ID'],
            xpEarned: 80
          }
        ]
      }
    ]
  },
  {
    id: 'sim_remote_01',
    title: 'Remote Access Scam: The AnyDesk Screen Hijack',
    category: 'Remote Access',
    difficulty: 'Intermediate',
    estimatedMinutes: 4,
    tagline: 'An executive says: "Install QuickSupport so our engineer can fix your payment refund cache."',
    realWorldContext: 'Remote desktop applications (AnyDesk, TeamViewer, RustDesk) allow fraudsters to view your phone screen and copy incoming OTPs in real-time.',
    iconName: 'Smartphone',
    victimLossStat: 'One of the highest single-victim loss categories, frequently exceeding ₹5-10 Lakhs',
    learningTakeaways: [
      'NEVER install AnyDesk, TeamViewer, or QuickSupport at the instruction of an incoming caller.',
      'Sharing your 9-digit remote access code gives strangers complete control over your phone and camera.',
      'Bank and UPI executives will NEVER ask for screen sharing permissions.'
    ],
    steps: [
      {
        id: 'remote_step_1',
        prompt: 'The caller says: "Sir, open Play Store, search for \'AnyDesk\' and give me the 9-digit address so we can synchronize your UPI address."',
        contextNarrative: 'The app is downloaded from official Google Play Store, so you wonder if it is safe.',
        screenType: 'generic',
        screenMockupData: {
          appBrand: 'AnyDesk Remote Desktop',
          messageText: 'Your Address: 492 819 104. Allow remote user to view and control this device?'
        },
        options: [
          {
            id: 'opt_remote_give_code',
            text: 'Read the 9-digit code to the technician since the app is legitimately on Google Play.',
            isSafe: false,
            explanation: 'Disaster! While AnyDesk is legitimate software for IT admins, giving your code allows the scammer to see your NetBanking passwords and incoming OTPs!',
            redFlagsDiscovered: ['Legitimate utility misused as Trojan horse', 'Screen monitoring allows stealing OTPs without user realizing', 'Tech support asking for device control'],
            xpEarned: 0
          },
          {
            id: 'opt_remote_terminate',
            text: 'Refuse firmly, hang up, and immediately uninstall the remote tool if downloaded.',
            isSafe: true,
            explanation: 'Top-tier safety awareness! Legitimate banking and fintech apps have zero requirement for screen sharing tools.',
            redFlagsDiscovered: ['Remote screen capture danger', 'Violation of banking security protocols'],
            xpEarned: 90
          }
        ]
      }
    ]
  },
  {
    id: 'sim_govt_01',
    title: 'Fake Government Scheme: Subsidy & Grant Fraud',
    category: 'Fake Govt Scheme',
    difficulty: 'Beginner',
    estimatedMinutes: 3,
    tagline: '"PM Youth Digital Scheme: Free Laptop and ₹50,000 allowance for every student."',
    realWorldContext: 'Fake banners with national emblems and minister photos spread rapidly on family WhatsApp groups.',
    iconName: 'Award',
    victimLossStat: 'Targeting students, rural families, and senior citizens with fake registration fees',
    learningTakeaways: [
      'Genuine central & state government schemes are strictly hosted on `.gov.in` or `.nic.in` domains.',
      'Government welfare schemes never require a "processing fee" sent to a personal UPI ID.',
      'Verify any scheme on the official PIB Fact Check portal (factcheck.pib.gov.in).'
    ],
    steps: [
      {
        id: 'govt_step_1',
        prompt: 'You receive a forwarded WhatsApp message with official government emblems claiming: "PM Free Smartphone Yojana 2026. Register at http://pm-yojana-free-device.xyz and pay ₹99 postal fee."',
        contextNarrative: 'The message was forwarded by a well-meaning family relative.',
        screenType: 'whatsapp',
        screenMockupData: {
          sender: 'Forwarded many times',
          messageText: 'All Indian citizens eligible. Only 500 units left! Register before midnight.'
        },
        options: [
          {
            id: 'opt_govt_pay_fee',
            text: 'It is only ₹99, so fill your Aadhaar number and pay ₹99 just in case it is real.',
            isSafe: false,
            explanation: 'Loss of money and sensitive identity data! Your Aadhaar and payment details are sold on fraud networks.',
            redFlagsDiscovered: ['Non-government domain (.xyz)', 'Unsolicited forward with high urgency', 'Charging fees for supposed free welfare'],
            xpEarned: 0
          },
          {
            id: 'opt_govt_check_pib',
            text: 'Check PIB Fact Check or the official portal mygov.in to confirm if this scheme exists.',
            isSafe: true,
            explanation: 'PIB Fact Check has officially flagged this exact message as 100% fake. Excellent vigilance!',
            redFlagsDiscovered: ['Fake government URL', 'Aadhaar harvesting trap'],
            xpEarned: 80
          }
        ]
      }
    ]
  },
  {
    id: 'sim_cc_01',
    title: 'Credit Card Scam: Card Limit Enhancement Fraud',
    category: 'Credit Card CVV',
    difficulty: 'Intermediate',
    estimatedMinutes: 4,
    tagline: '"Sir, you are pre-approved for an instant credit limit upgrade from ₹1 Lakh to ₹5 Lakhs."',
    realWorldContext: 'Callers impersonate card issuance departments, offering free upgrades and asking for card digits to "validate".',
    iconName: 'CreditCard',
    victimLossStat: 'Pre-approved limit traps steal CVV and OTP to execute immediate e-commerce gift card orders',
    learningTakeaways: [
      'Card limit upgrades are done directly inside your bank app with 1-click toggle, without asking for CVV.',
      'CVV and Card Expiry should NEVER be spoken over a voice call.',
      'Bank reps cannot see your 3-digit CVV and are forbidden from asking for it.'
    ],
    steps: [
      {
        id: 'cc_step_1',
        prompt: 'The caller says: "Sir, to apply the ₹5,00,000 limit upgrade on your ICICI Visa card ending in 4102, please read the 3-digit security code on the back of the card."',
        contextNarrative: 'They already know your name and the last 4 digits of your card, making them sound genuine.',
        screenType: 'phone_call',
        screenMockupData: {
          sender: '+91 97182 10928 (Caller: ICICI Upgrade Desk)',
          messageText: '"I just need to confirm the CVV code to trigger the server sync."'
        },
        options: [
          {
            id: 'opt_cc_share_cvv',
            text: 'Share the CVV since they already know your name and last 4 card digits.',
            isSafe: false,
            explanation: 'Critical card breach! Scammers buy leaked basic card numbers from data breaches; the CVV is the final key needed to charge transactions!',
            redFlagsDiscovered: ['Requesting 3-digit CVV over phone', 'Using leaked basic data to fabricate legitimacy'],
            xpEarned: 0
          },
          {
            id: 'opt_cc_refuse_cvv',
            text: 'Refuse: "CVV is strictly confidential. If my card is eligible for upgrade, I will enable it inside the official iMobile app."',
            isSafe: true,
            explanation: 'Spot on! True bank limit upgrades are accepted inside NetBanking or authenticated mobile app without revealing CVV.',
            redFlagsDiscovered: ['CVV solicitation over voice call', 'Social engineering via partial card knowledge'],
            xpEarned: 85
          }
        ]
      }
    ]
  },
  {
    id: 'sim_social_01',
    title: 'Social Engineering: The "Digital Arrest" Extortion',
    category: 'Social Engineering',
    difficulty: 'Expert',
    estimatedMinutes: 5,
    tagline: 'A video call from a "CBI Officer" sitting in front of a police backdrop threatens immediate arrest.',
    realWorldContext: 'Syndicates create realistic police station sets, fake arrest warrants with government seals, and keep victims on continuous video call for days.',
    iconName: 'UserX',
    victimLossStat: 'Senior citizens have lost their entire retirement life savings in "Digital Arrest" schemes in recent months',
    learningTakeaways: [
      'THERE IS NO SUCH THING AS "DIGITAL ARREST" IN INDIAN LAW OR ANY LAW WORLDWIDE.',
      'Police, CBI, ED, and Customs never interrogate or place citizens under arrest via Skype or WhatsApp video call.',
      'Never transfer money to "RBI Reserve Escrow Accounts" for clearance or verification.'
    ],
    steps: [
      {
        id: 'social_step_1',
        prompt: 'You receive an urgent video call from "DCP Crime Branch". The officer is in full uniform with Indian flag and police emblems behind him.',
        contextNarrative: '"A courier containing 140 grams of MDMA drugs and fake passports sent from Mumbai to Taiwan has your Aadhaar number linked to it. The Supreme Court has issued an arrest warrant."',
        screenType: 'phone_call',
        screenMockupData: {
          sender: 'DCP Crime Branch (Video Call)',
          messageText: '"You are under Digital Arrest. You are prohibited from disconnecting this call or speaking to family until cleared."'
        },
        options: [
          {
            id: 'opt_social_panic_comply',
            text: 'Stay on the video call, follow his orders, and transfer your savings to the "Verification Account" to clear your name.',
            isSafe: false,
            explanation: 'Catastrophic Error! This is the notorious "Digital Arrest" fraud. Millions have been stolen through this exact scripted psychological fear trap.',
            redFlagsDiscovered: ['Non-existent concept of "Digital Arrest"', 'Demand to transfer personal funds for verification', 'Coercion to isolate victim from family and lawyers'],
            xpEarned: 0
          },
          {
            id: 'opt_social_call_police_station',
            text: 'Hang up immediately. Walk to your local police station or dial 1930/112 to report the extortion attempt.',
            isSafe: true,
            explanation: 'Bravo! Genuine law enforcement issues formal physical summons. They NEVER demand money or conduct trials over video calls.',
            redFlagsDiscovered: ['Supreme Court/CBI spoofing', 'Emotional panic and hostage psychology'],
            xpEarned: 100
          }
        ]
      }
    ]
  }
];

export const FRAUD_NEWS_ARTICLES: NewsArticle[] = [
  {
    id: 'news_01',
    headline: 'Retired Executive Duped of ₹3.8 Crore in 72-Hour "Digital Arrest" Ordeal in Bengaluru',
    category: 'Deepfake & Voice',
    riskLevel: 'CRITICAL',
    location: 'Bengaluru, Karnataka',
    date: 'Oct 3, 2026',
    estimatedLoss: '₹3.80 Crore',
    readTime: '4 min read',
    summary: 'A 68-year-old retired PSU director was kept under continuous Skype surveillance by criminals posing as Mumbai Police and CBI officers, coercing him into liquidating mutual funds.',
    whatHappened: 'The victim received a call alleging a DHL parcel with forged passports and narcotics had been intercepted in his name. Scammers staged a mock police station room with authentic-looking uniform, badges, and forged court seals.',
    howScamWorked: [
      'Initial cold call claiming customs parcel seizure',
      'Transfer to fake police video station with police backdrops',
      'Presentation of forged Supreme Court non-bailable arrest warrants',
      'Coercion to keep video call active 24/7 without notifying spouse or children',
      'Demanding full fund transfer to "Secret RBI Verification Escrow" which was actually mule bank accounts'
    ],
    redFlags: [
      'Arrests are never conducted via Skype or WhatsApp video',
      'No law allows seizure of bank deposits for "verification"',
      'Extreme urgency and pressure to maintain total secrecy'
    ],
    howToStaySafe: [
      'Disconnect suspicious calls immediately and report to 1930.',
      'Check facts with your local police station.',
      'Remember: Genuine police never demand online fund transfers.'
    ],
    relatedSimulationId: 'sim_social_01',
    relatedCategory: 'Social Engineering',
    source: 'National Cyber Security Bulletin'
  },
  {
    id: 'news_02',
    headline: 'Fake Stock Trading App Syndicate Busted in Mumbai; 12 Arrested with 450 Mule Accounts',
    category: 'Investment Fraud',
    riskLevel: 'CRITICAL',
    location: 'Mumbai, Maharashtra',
    date: 'Sep 28, 2026',
    estimatedLoss: '₹42 Crore',
    readTime: '3 min read',
    summary: 'Cyber police dismantled an international network operating cloned trading applications that lured tech professionals through high-yield institutional trading groups.',
    whatHappened: 'Victims were recruited through Instagram ads promising access to institutional IPO allocations. The app displayed artificial 500% gains, but refused withdrawals unless a 25% "securities transaction tax" was deposited.',
    howScamWorked: [
      'WhatsApp/Telegram group invitation with fake profits screenshots',
      'Installation of customized APK mimicking reputed broking platforms',
      'Simulated profit generation on user dashboard',
      'Sudden freeze on withdrawals demanding advance taxes'
    ],
    redFlags: [
      'Brokers operating exclusively via WhatsApp groups',
      'Deposits requested to personal savings accounts instead of clearing corporations',
      'Unrealistic guaranteed returns'
    ],
    howToStaySafe: [
      'Trade only through SEBI-registered brokers listed on NSE/BSE.',
      'Never install financial APKs outside the official Google Play or Apple App Store.',
      'Cross-check broker registration numbers on sebi.gov.in.'
    ],
    relatedSimulationId: 'sim_invest_01',
    relatedCategory: 'Investment Fraud',
    source: 'Financial Express Cyber Desk'
  },
  {
    id: 'news_03',
    headline: 'Electricity Bill Disconnection SMS Gang Targeted 15,000 Consumers Across Western India',
    category: 'Refund Scam',
    riskLevel: 'HIGH',
    location: 'Ahmedabad & Pune',
    date: 'Sep 19, 2026',
    estimatedLoss: '₹6.2 Crore',
    readTime: '3 min read',
    summary: 'Fraudsters sent mass SMS warnings late at night threatening power disconnection within 60 minutes, duping residents into installing screen-sharing tools.',
    whatHappened: 'When alarmed citizens called the mobile numbers in the SMS, operators asked them to pay a nominal ₹10 verification charge via a provided link or install AnyDesk to clear the server backlog.',
    howScamWorked: [
      'Timing SMS blasts between 8 PM and 10 PM to create acute urgency',
      'Impersonating official electricity discom officers',
      'Directing victims to install remote desktop tools or phishing gateways',
      'Stealing credentials during the ₹10 transaction'
    ],
    redFlags: [
      'SMS sent from standard 10-digit mobile numbers (+91...) instead of registered sender IDs',
      'Absence of consumer ID or meter number in the SMS',
      'Insistence on downloading remote support apps'
    ],
    howToStaySafe: [
      'Pay bills exclusively via authorized utility apps or Bharat BillPay (BBPS).',
      'Power boards never issue immediate disconnection notices via SMS.',
      'Never call personal phone numbers provided in alert SMS messages.'
    ],
    relatedSimulationId: 'sim_refund_01',
    relatedCategory: 'Refund Scam',
    source: 'Cyber Crime Investigation Department'
  },
  {
    id: 'news_04',
    headline: 'NPCI Issues New Advisory on QR Code Inversion Tactics Used on Second-Hand Marketplaces',
    category: 'QR Code Scam',
    riskLevel: 'HIGH',
    location: 'National / Pan-India',
    date: 'Sep 12, 2026',
    estimatedLoss: '₹140 Crore',
    readTime: '2 min read',
    summary: 'The National Payments Corporation of India (NPCI) launched nationwide safety guidelines educating consumers that QR codes are solely for debiting money.',
    whatHappened: 'Online marketplace sellers continue falling for claims that scanning a buyer\'s QR code or entering a UPI PIN is required to receive pending sales proceeds or advance deposits.',
    howScamWorked: [
      'Scammer poses as prospective buyer eager to buy without bargaining',
      'Shares QR code disguised as "Merchant Receive Barcode"',
      'Instructs seller to scan and key in UPI PIN to "authenticate"',
      'Funds debited instantaneously from seller\'s account'
    ],
    redFlags: [
      'Any claim that receiving money requires scanning QR or entering PIN',
      'Buyers unwilling to verify identity or visit physically',
      'Overpayment claims followed by refund demands'
    ],
    howToStaySafe: [
      'Remember the golden rule: UPI PIN is ONLY entered to deduct money.',
      'To receive money, simply share your mobile number or UPI ID.',
      'Never scan barcodes sent over WhatsApp.'
    ],
    relatedSimulationId: 'sim_qr_01',
    relatedCategory: 'QR Code Scam',
    source: 'NPCI Public Safety Bulletin'
  }
];

export const COURSE_MODULES: CourseModule[] = [
  {
    id: 'course_01',
    title: 'Digital Payments 101: The UPI Architecture & Security',
    track: 'Beginner',
    category: 'UPI Collect',
    durationMinutes: 12,
    xpReward: 150,
    description: 'Master the fundamental mechanics of UPI, VPA, Collect Requests, and why you never need a PIN to receive payments.',
    sections: [
      {
        heading: '1. The Cardinal Rule of UPI PIN',
        content: 'Your UPI PIN is like your ATM PIN or NetBanking password. You use it ONLY when money leaves your bank account. To receive money, the sender only needs your mobile number or UPI ID (e.g., name@okaxis). No PIN, no OTP, and no biometric fingerprint is ever needed to receive funds.',
        goldenRule: 'PIN = PAY. If you are entering your PIN, money is leaving your account.'
      },
      {
        heading: '2. Anatomy of a Collect Request',
        content: 'UPI features a "Collect" mechanism where a merchant or person requests money from you. Scammers send collect requests titled "Refund", "Cashback Voucher", or "Salary Credit" with an amount like ₹4,999. If you tap "Pay", the money is transferred to the scammer.',
        goldenRule: 'Check the button: If it says "PAY" or "APPROVE", you are sending money, not receiving.'
      }
    ],
    quizQuestions: [
      {
        question: 'When is entering your UPI PIN required?',
        options: [
          'When sending money or making a purchase',
          'When receiving an online refund',
          'When scanning a QR code to accept cash',
          'When checking if your account is active'
        ],
        correctIndex: 0,
        explanation: 'You only ever enter your UPI PIN to authenticate an outgoing debit.'
      }
    ]
  },
  {
    id: 'course_02',
    title: 'Phishing & Domain Forensics: Spotting Fake Portals',
    track: 'Intermediate',
    category: 'Phishing Link',
    durationMinutes: 18,
    xpReward: 200,
    description: 'Learn how cybercriminals clone legitimate banking sites, spoof sender IDs, and disguise malicious URLs.',
    sections: [
      {
        heading: '1. Reading Domain Names Like a Security Pro',
        content: 'A domain name is read from right to left before the first slash. For example, in `onlinesbi.sbi/login`, the official domain is `sbi`. But in `sbi-kyc-update.portal-secure.xyz/login`, the actual domain is `portal-secure.xyz`! Scammers prefix brand names as subdomains to fool users.',
        goldenRule: 'Always check the domain right before the first slash.'
      },
      {
        heading: '2. The Danger of SMS Shorteners',
        content: 'Links using bit.ly, tinyurl, or custom redirects hide the destination server. Always expand or inspect unfamiliar links, or better yet, open your official mobile app directly.',
        goldenRule: 'Never click links in SMS claiming your account is suspended or points are expiring.'
      }
    ],
    quizQuestions: [
      {
        question: 'Which of the following is the legitimate State Bank of India domain?',
        options: [
          'http://sbi-verification-secure.com',
          'https://onlinesbi.sbi',
          'https://sbi-online.update.in',
          'https://bank-sbi-portal.org'
        ],
        correctIndex: 1,
        explanation: 'State Bank of India owns the exclusive `.sbi` top-level domain.'
      }
    ]
  },
  {
    id: 'course_03',
    title: 'Social Engineering & Psychological Manipulation Defenses',
    track: 'Advanced',
    category: 'Social Engineering',
    durationMinutes: 20,
    xpReward: 250,
    description: 'Understand the cognitive biases scammers exploit: artificial urgency, fear of prosecution, greed, and authority intimidation.',
    sections: [
      {
        heading: '1. The "Amydala Hijack" Technique',
        content: 'When told your electricity will be cut off in 30 minutes, or you face immediate arrest by CBI, your brain triggers a fight-or-flight response. Scammers intentionally manufacture extreme time pressure to stop you from consulting family or thinking logically.',
        goldenRule: 'When panic strikes, pause for 10 minutes. Legitimate institutions never force 60-second decisions.'
      },
      {
        heading: '2. The Digital Arrest Myth',
        content: 'Under criminal procedure, no law allows detention via video conference. Law enforcement agencies never conduct trials or demand bank fund transfers over Skype, WhatsApp, or Google Meet.',
        goldenRule: 'Any video call claiming you are "under arrest" is 100% fraud. Hang up and report.'
      }
    ],
    quizQuestions: [
      {
        question: 'What is the immediate best step if a caller claims you are under "Digital Arrest"?',
        options: [
          'Stay on camera and transfer funds to the verification account',
          'Disconnect immediately, block the number, and dial 1930 / visit local police station',
          'Ask the caller for a 10% discount on the fine',
          'Forward the link to your friends'
        ],
        correctIndex: 1,
        explanation: 'Digital Arrest does not exist in law. Disconnect and report immediately.'
      }
    ]
  }
];

export const LEARNING_PATH_NODES: LearningPathNode[] = [
  {
    id: 'path_node_1',
    title: 'The Golden Rule of UPI',
    levelNumber: 1,
    category: 'UPI Collect',
    isUnlocked: true,
    isCompleted: true,
    xpReward: 100,
    icon: 'ShieldCheck',
    description: 'Learn why PIN always means pay and how to prevent accidental money transfers.',
    simulationId: 'sim_upi_collect_01'
  },
  {
    id: 'path_node_2',
    title: 'OTP Defense Mastery',
    levelNumber: 2,
    category: 'OTP Fraud',
    isUnlocked: true,
    isCompleted: true,
    xpReward: 120,
    icon: 'KeyRound',
    description: 'Defeat social engineering tactics attempting to read your one-time passwords.',
    simulationId: 'sim_otp_01'
  },
  {
    id: 'path_node_3',
    title: 'The QR Code Inversion Trap',
    levelNumber: 3,
    category: 'QR Code Scam',
    isUnlocked: true,
    isCompleted: true,
    xpReward: 150,
    icon: 'QrCode',
    description: 'Protect your marketplace sales and never scan barcodes to receive money.',
    simulationId: 'sim_qr_01'
  },
  {
    id: 'path_node_4',
    title: 'KYC & Account Suspension Phishing',
    levelNumber: 4,
    category: 'KYC Scam',
    isUnlocked: true,
    isCompleted: true,
    xpReward: 180,
    icon: 'AlertTriangle',
    description: 'Unmask fake bank SMS alerts and protect your PAN and Aadhaar credentials.',
    simulationId: 'sim_kyc_01'
  },
  {
    id: 'path_node_5',
    title: 'Remote Screen Sharing Trojans',
    levelNumber: 5,
    category: 'Remote Access',
    isUnlocked: true,
    isCompleted: false,
    xpReward: 200,
    icon: 'Smartphone',
    description: 'Prevent fraudsters from seizing control of your mobile device via AnyDesk.',
    simulationId: 'sim_remote_01'
  },
  {
    id: 'path_node_6',
    title: 'Pig Butchering & Crypto Frauds',
    levelNumber: 6,
    category: 'Investment Fraud',
    isUnlocked: false,
    isCompleted: false,
    xpReward: 250,
    icon: 'TrendingUp',
    description: 'Dismantle fake stock trading groups and artificial profit dashboard scams.',
    simulationId: 'sim_invest_01'
  },
  {
    id: 'path_node_7',
    title: 'Deepfakes & AI Voice Extortion',
    levelNumber: 7,
    category: 'Deepfake & Voice',
    isUnlocked: false,
    isCompleted: false,
    xpReward: 300,
    icon: 'Mic',
    description: 'Detect cloned voices and establish secret emergency protocols for your family.',
    simulationId: 'sim_deepfake_01'
  },
  {
    id: 'path_node_8',
    title: 'The "Digital Arrest" Psyops Protocol',
    levelNumber: 8,
    category: 'Social Engineering',
    isUnlocked: false,
    isCompleted: false,
    xpReward: 400,
    icon: 'Award',
    description: 'Master defense against aggressive psychological extortion and fake law enforcement.',
    simulationId: 'sim_social_01'
  }
];

export const ACHIEVEMENTS_DATA: AchievementItem[] = [
  {
    id: 'ach_otp_master',
    name: 'OTP Master',
    title: 'Ironclad Vault',
    description: 'Successfully rejected 5 consecutive attempts to harvest your OTP credentials.',
    icon: 'KeyRound',
    progress: 5,
    maxProgress: 5,
    category: 'OTP Safety',
    unlockedAt: 'Oct 2, 2026'
  },
  {
    id: 'ach_qr_hunter',
    name: 'QR Hunter',
    title: 'Barcode Detective',
    description: 'Identified and reported 3 fraudulent "Scan to Receive Money" marketplace lures.',
    icon: 'QrCode',
    progress: 3,
    maxProgress: 3,
    category: 'QR Safety',
    unlockedAt: 'Sep 29, 2026'
  },
  {
    id: 'ach_phish_expert',
    name: 'Phishing Expert',
    title: 'URL Inspector',
    description: 'Inspected 10 suspicious domain names and caught fake banking web portals.',
    icon: 'ExternalLink',
    progress: 7,
    maxProgress: 10,
    category: 'Web Security'
  },
  {
    id: 'ach_scam_detective',
    name: 'Scam Detective',
    title: 'Fraud Investigator',
    description: 'Completed 8 diverse fraud simulations with 100% safety score.',
    icon: 'Search',
    progress: 4,
    maxProgress: 8,
    category: 'Simulations'
  },
  {
    id: 'ach_first_blood',
    name: 'Fraud Defender',
    title: 'Active Guardian',
    description: 'Passed your first live scam simulation and saved your virtual account.',
    icon: 'ShieldCheck',
    progress: 1,
    maxProgress: 1,
    category: 'General',
    unlockedAt: 'Sep 20, 2026'
  },
  {
    id: 'ach_streak_7',
    name: 'Cyber Guardian',
    title: 'Daily Vigilance',
    description: 'Maintained an unbroken 7-day fraud awareness training streak.',
    icon: 'Flame',
    progress: 7,
    maxProgress: 7,
    category: 'Streak',
    unlockedAt: 'Today'
  },
  {
    id: 'ach_voice_shield',
    name: 'Voice Shield',
    title: 'Audio Forensics',
    description: 'Identified synthetic deepfake speech artifacts during a live phone simulation.',
    icon: 'Mic',
    progress: 1,
    maxProgress: 2,
    category: 'Voice'
  },
  {
    id: 'ach_elite_learner',
    name: 'Elite Learner',
    title: 'Certified Shield Master',
    description: 'Achieved an overall Fraud Awareness Score of 85+ and earned the Master Certificate.',
    icon: 'Award',
    progress: 84,
    maxProgress: 85,
    category: 'Score'
  }
];

export const LEADERBOARD_USERS: LeaderboardUser[] = [
  {
    rank: 1,
    name: 'Aarav Deshmukh',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    institution: 'IIT Bombay',
    xp: 4820,
    level: 9,
    shieldBadge: 'Elite Cyber Sentinel',
    streak: 34
  },
  {
    rank: 2,
    name: 'Priyanka Sen',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    institution: 'BITS Pilani',
    xp: 4210,
    level: 8,
    shieldBadge: 'Master Fraud Detective',
    streak: 28
  },
  {
    rank: 3,
    name: 'Rohan Varma',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    institution: 'HDFC Bank Security Ops',
    xp: 3950,
    level: 8,
    shieldBadge: 'Cyber Guardian',
    streak: 21
  },
  {
    rank: 4,
    name: 'Harshal Mahajan',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    institution: 'National Institute of Tech',
    xp: 1450,
    level: 4,
    shieldBadge: 'Senior Cyber Defender',
    streak: 7,
    isCurrentUser: true
  },
  {
    rank: 5,
    name: 'Ananya Iyer',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    institution: 'IIM Ahmedabad',
    xp: 1390,
    level: 4,
    shieldBadge: 'Cyber Defender',
    streak: 12
  },
  {
    rank: 6,
    name: 'Vikram Joshi',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    institution: 'State Bank of India',
    xp: 1240,
    level: 3,
    shieldBadge: 'Vigilant Shield',
    streak: 6
  }
];

export const VOICE_SCENARIOS: VoiceScenario[] = [
  {
    id: 'voice_scen_1',
    callerName: 'Inspector Rajesh Chauhan',
    callerTitle: 'Cyber Crime Investigation Cell, Delhi',
    organization: 'Delhi Police / National Cyber Crime Portal',
    initialTranscript: '"Greetings. This is Inspector Chauhan speaking directly from Cyber Crime Cell Delhi. A money laundering bank account in your name with ₹45 Lakhs illegal deposits has been flagged under PMLA. Are you aware of this investigation?"',
    dialogueScript: [
      {
        callerText: '"Sir, an immediate Non-Bailable Warrant has been approved by the Magistrate. To stop police squad deployment to your residential address, you must verify your identity immediately. Are you alone right now?"',
        options: [
          {
            userReply: '"Yes sir, I am alone. Please don\'t send police! What do I need to do to clear this?"',
            callerReaction: '"Good. Now install this official encrypted clearance application immediately and transfer your liquid deposits for forensic audit."',
            isSafe: false,
            points: 0,
            feedback: 'You yielded to fear. Police never offer "instant online clearance" or demand secrecy.',
            detectedFlags: ['Panic submission', 'Isolation pressure']
          },
          {
            userReply: '"Police investigations do not happen over informal phone calls. Please serve a formal notice under CrPC Section 41A, and I will appear with legal counsel."',
            callerReaction: '"Sir... you are obstructing government duty... (Voice hesitates and caller becomes defensive)."',
            isSafe: true,
            points: 50,
            feedback: 'Masterful response! Demanding formal legal procedure under CrPC 41A immediately disarms scam operators.',
            detectedFlags: ['Disarmed authority intimidation', 'Enforced legal protocol']
          }
        ]
      },
      {
        callerText: '"You are challenging police authority! We are freezing your PAN and Aadhaar in 15 minutes unless you verify your bank credentials!"',
        options: [
          {
            userReply: '"I will immediately contact my local police station and report this call to 1930. Goodbye."',
            callerReaction: 'The scammer abruptly disconnects the call.',
            isSafe: true,
            points: 50,
            feedback: 'Flawless execution. Calling their bluff and mentioning the 1930 cyber helpline causes fraudsters to flee.',
            detectedFlags: ['Reported to national helpline', 'Zero credential disclosure']
          },
          {
            userReply: '"Wait, wait! I can verify my bank name and account balance, just please don\'t block my PAN!"',
            callerReaction: '"Read out your account number and last transaction amount quickly!"',
            isSafe: false,
            points: 0,
            feedback: 'Never provide financial disclosures out of panic.',
            detectedFlags: ['Information harvesting under duress']
          }
        ]
      }
    ],
    summaryAdvice: 'Real police officers NEVER demand money transfers, video interrogations, or secrecy. Always call 1930 or visit your local police station.'
  },
  {
    id: 'voice_scen_2',
    callerName: 'Pooja Hegde (Senior Fraud Desk)',
    callerTitle: 'Debit Card Security Team',
    organization: 'HDFC Bank Head Office',
    initialTranscript: '"Good afternoon, this is Pooja from HDFC Bank Card Security Desk. We have temporarily blocked an overseas transaction of ₹28,400 initiated on your debit card on Amazon UK. Did you make this purchase?"',
    dialogueScript: [
      {
        callerText: '"Since you did not make this purchase, I am processing the instant reversal. To cancel the charge on our gateway, please read the 6-digit verification code just delivered to your mobile."',
        options: [
          {
            userReply: '"Wait, the SMS says \'OTP for transaction of ₹28,400\'. Why does it say transaction if it is a cancellation?"',
            callerReaction: '"Sir, that is standard bank server wording. Please read it quickly before the session expires!"',
            isSafe: true,
            points: 50,
            feedback: 'Spotting the contradiction between the SMS text and the caller\'s claim saved your money!',
            detectedFlags: ['Identified OTP transaction wording contradiction']
          },
          {
            userReply: '"Okay, the 6 digits are 4-9-2-0-1-8. Please hurry and cancel it!"',
            callerReaction: '"Thank you sir, transaction approved... (Call disconnects. Balance debited)."',
            isSafe: false,
            points: 0,
            feedback: 'You authorized the scammer\'s purchase on Amazon UK.',
            detectedFlags: ['OTP disclosure to caller']
          }
        ]
      }
    ],
    summaryAdvice: 'Banks never need an OTP from you to cancel unauthorized charges. OTP is exclusively for debiting accounts.'
  }
];

export const SMS_SIMULATION_ITEMS: SMSItem[] = [
  {
    id: 'sms_01',
    senderId: 'VM-EPFOKYC',
    header: 'EPFO Compliance Alert',
    timestamp: 'Today, 10:14 AM',
    body: 'Dear Member, your EPFO Universal Account (UAN) is temporarily suspended due to mismatch in Aadhaar details. Click https://epfindia-gov-uan.top/kyc to link your profile to avoid interest penalty.',
    isScam: true,
    category: 'KYC Scam',
    redFlags: [
      'Unverified domain extension (.top) instead of official epfindia.gov.in',
      'Threat of interest penalty to create panic',
      'EPFO never updates UAN details via unsolicited SMS links'
    ],
    safeExplanation: 'The legitimate portal is epfindia.gov.in. Any domain ending in .top, .vip, or .xyz is a credential-harvesting trap.'
  },
  {
    id: 'sms_02',
    senderId: 'JD-HDFCBK',
    header: 'HDFC Bank Official Alert',
    timestamp: 'Yesterday, 3:20 PM',
    body: 'Dear Customer, ₹2,500.00 debited from A/C **4102 on 06-OCT-26 via UPI to ZOMATO LTD. Ref 429104819. If not done by you, call 1800-258-3838 or SMS BLOCK to 5676712.',
    isScam: false,
    category: 'OTP Fraud',
    redFlags: [],
    safeExplanation: 'This is a genuine transactional notification. It contains authentic toll-free numbers, the official masked account format, and no suspicious web links.'
  },
  {
    id: 'sms_03',
    senderId: 'BZ-FEDEXIN',
    header: 'FedEx Parcel Detained',
    timestamp: 'Oct 5, 8:45 PM',
    body: 'FedEx: Your overseas parcel #FX-92819 has failed customs clearance due to missing address info. Update your details and pay ₹14.50 re-delivery surcharge at http://fedex-parcel-tracking.site/in before item is forfeited.',
    isScam: true,
    category: 'Phishing Link',
    redFlags: [
      'Fake domain `fedex-parcel-tracking.site` instead of official fedex.com',
      'Tiny fee lure (₹14.50) designed to trick users into entering credit card details',
      'Forfeiture threat pressure'
    ],
    safeExplanation: 'The tiny fee is bait. The credit card form captures your CVV and triggers unauthorized high-value debits.'
  },
  {
    id: 'sms_04',
    senderId: 'VM-SBIINB',
    header: 'SBI Rewards Expiry',
    timestamp: 'Oct 4, 11:30 AM',
    body: 'Congratulations! You have 9,850 unused SBI Reward Points worth ₹4,925 expiring tonight at 11:59 PM. Redeem immediately for direct cash back: http://onlinesbi-rewards-redeem.click/gift',
    isScam: true,
    category: 'Phishing Link',
    redFlags: [
      'Domain uses `.click` TLD instead of `.sbi`',
      'Manufactured urgency ("expiring tonight at 11:59 PM")',
      'Banks do not provide direct cash credit via third-party web forms'
    ],
    safeExplanation: 'SBI rewards are redeemed securely inside SBI YONO or the official sbi.co.in banking portal.'
  }
];

export const HEATMAP_DATA_INDIA: HeatmapStateData[] = [
  {
    stateId: 'MH',
    stateName: 'Maharashtra',
    reportedCasesCount: 184500,
    topScamType: 'Social Engineering',
    riskSeverity: 'Critical Hotspot',
    avgVictimLoss: '₹94,000',
    growthRate: '+38% YoY'
  },
  {
    stateId: 'DL',
    stateName: 'Delhi-NCR',
    reportedCasesCount: 142000,
    topScamType: 'Deepfake & Voice',
    riskSeverity: 'Critical Hotspot',
    avgVictimLoss: '₹1,12,000',
    growthRate: '+44% YoY'
  },
  {
    stateId: 'KA',
    stateName: 'Karnataka',
    reportedCasesCount: 128900,
    topScamType: 'Investment Fraud',
    riskSeverity: 'High Alert',
    avgVictimLoss: '₹1,45,000',
    growthRate: '+29% YoY'
  },
  {
    stateId: 'TG',
    stateName: 'Telangana',
    reportedCasesCount: 96400,
    topScamType: 'UPI Collect',
    riskSeverity: 'High Alert',
    avgVictimLoss: '₹76,000',
    growthRate: '+22% YoY'
  },
  {
    stateId: 'UP',
    stateName: 'Uttar Pradesh',
    reportedCasesCount: 165000,
    topScamType: 'OTP Fraud',
    riskSeverity: 'Critical Hotspot',
    avgVictimLoss: '₹48,000',
    growthRate: '+31% YoY'
  },
  {
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    reportedCasesCount: 82000,
    topScamType: 'Customer Support',
    riskSeverity: 'Moderate',
    avgVictimLoss: '₹55,000',
    growthRate: '+14% YoY'
  },
  {
    stateId: 'GJ',
    stateName: 'Gujarat',
    reportedCasesCount: 91500,
    topScamType: 'Investment Fraud',
    riskSeverity: 'High Alert',
    avgVictimLoss: '₹1,20,000',
    growthRate: '+27% YoY'
  },
  {
    stateId: 'WB',
    stateName: 'West Bengal',
    reportedCasesCount: 74200,
    topScamType: 'KYC Scam',
    riskSeverity: 'Moderate',
    avgVictimLoss: '₹42,000',
    growthRate: '+18% YoY'
  }
];

export const GLOBAL_HEATMAP_REGIONS = [
  { country: 'India', cases: '1,420,000', topScam: 'UPI & Digital Arrest Extortion', risk: 'Critical Hotspot' },
  { country: 'United States', cases: '2,150,000', topScam: 'Crypto Pig Butchering & Tech Support', risk: 'Critical Hotspot' },
  { country: 'United Kingdom', cases: '680,000', topScam: 'Authorized Push Payment (APP) Fraud', risk: 'High Alert' },
  { country: 'Singapore', cases: '145,000', topScam: 'Job & E-commerce Impersonation', risk: 'High Alert' },
  { country: 'Australia', cases: '320,000', topScam: 'Investment Schemes & SMS Smishing', risk: 'High Alert' },
  { country: 'Canada', cases: '410,000', topScam: 'Government Grant & CRA Tax Refund', risk: 'Moderate' }
];

export const CERTIFICATES_DATA = [
  {
    id: 'cert_guardian_01',
    name: 'Certified Digital Fraud Guardian',
    credentialCode: 'SCAMSHIELD-GRD-2026-9281',
    issueDate: 'October 4, 2026',
    grade: 'Distinction (Grade A+)',
    scorePercent: 94,
    levelTitle: 'Level 4 Defender',
    institutionBadge: 'ScamShield AI & National Cyber Training Alliance',
    skillsVerified: ['UPI Security Protocols', 'OTP Shielding', 'Digital Arrest Countermeasures', 'Phishing URL Forensics']
  },
  {
    id: 'cert_upi_01',
    name: 'UPI & Payment Gateway Safety Specialist',
    credentialCode: 'SCAMSHIELD-UPI-2026-4412',
    issueDate: 'September 28, 2026',
    grade: 'Mastery (Grade A)',
    scorePercent: 91,
    levelTitle: 'Payment Security Specialist',
    institutionBadge: 'Digital Payment Safety Council',
    skillsVerified: ['QR Code Decoupling', 'Collect Request Auditing', 'Toll-free Verification', 'PIN Debit Mechanics']
  }
];
